### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [stape-io/telegram-notification-tag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1)encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.token when generating the url
const url = 'https://api.telegram.org/bot'+data.token+'/sendMessage?chat_id='+encodeUriComponent(data.channel)+'&text='+encodeUriComponent(data.text);

**Comment by Bukashk0zzz** [comment]
Thanks for review. Issue fixed https://github.com/gtm-server/telegram-notification-tag/commit/9fe6119502f77c6b35a6f1aeb5c08a74b9f24c84
